from __future__ import annotations

SEED_STAFF = [
    {
        "id": 1,
        "name": "Miguel Angel",
        "role": "Barbero Senior",
        "specialty": "Fade & Barba",
        "initials": "MA",
        "status": "active",
        "clients": 312,
        "rating": 4.9,
    },
    {
        "id": 2,
        "name": "Laura Garcia",
        "role": "Estilista",
        "specialty": "Color & Tratamientos",
        "initials": "LG",
        "status": "active",
        "clients": 198,
        "rating": 4.8,
    },
    {
        "id": 3,
        "name": "Carlos Diaz",
        "role": "Barbero",
        "specialty": "Clasico & Diseno",
        "initials": "CD",
        "status": "active",
        "clients": 241,
        "rating": 4.7,
    },
    {
        "id": 4,
        "name": "Sofia Ramos",
        "role": "Estilista",
        "specialty": "Cortes Modernos",
        "initials": "SR",
        "status": "off",
        "clients": 155,
        "rating": 4.9,
    },
]

SEED_SERVICES = [
    {"id": 1, "name": "Corte Clasico", "category": "Corte", "price": 35000, "duration": 30, "popular": True},
    {"id": 2, "name": "Fade + Diseno", "category": "Corte", "price": 50000, "duration": 45, "popular": True},
    {"id": 3, "name": "Afeitado Tradicional", "category": "Barba", "price": 30000, "duration": 30, "popular": False},
    {"id": 4, "name": "Arreglo de Barba", "category": "Barba", "price": 25000, "duration": 20, "popular": True},
    {"id": 5, "name": "Corte + Barba", "category": "Combo", "price": 70000, "duration": 60, "popular": True},
    {"id": 6, "name": "Keratina Express", "category": "Tratamiento", "price": 120000, "duration": 90, "popular": False},
    {"id": 7, "name": "Coloracion Completa", "category": "Color", "price": 150000, "duration": 120, "popular": False},
    {"id": 8, "name": "Balayage", "category": "Color", "price": 200000, "duration": 150, "popular": False},
    {"id": 9, "name": "Hidratacion Profunda", "category": "Tratamiento", "price": 80000, "duration": 60, "popular": False},
    {"id": 10, "name": "Pompadour Premium", "category": "Corte", "price": 60000, "duration": 50, "popular": False},
]

SEED_APPOINTMENTS = [
    {
        "id": 1,
        "client": "Sebastian Ruiz",
        "initials": "SR",
        "service": "Fade + Diseno",
        "barber": "Miguel Angel",
        "time": "09:00",
        "duration": 45,
        "status": "confirmed",
        "visits": 14,
    },
    {
        "id": 2,
        "client": "Valentina Torres",
        "initials": "VT",
        "service": "Coloracion Completa",
        "barber": "Laura Garcia",
        "time": "09:30",
        "duration": 120,
        "status": "confirmed",
        "visits": 7,
    },
    {
        "id": 3,
        "client": "Andres Molina",
        "initials": "AM",
        "service": "Afeitado Tradicional",
        "barber": "Carlos Diaz",
        "time": "10:00",
        "duration": 30,
        "status": "checkin",
        "visits": 22,
    },
    {
        "id": 4,
        "client": "Camila Herrera",
        "initials": "CH",
        "service": "Hidratacion Profunda",
        "barber": "Laura Garcia",
        "time": "10:30",
        "duration": 60,
        "status": "confirmed",
        "visits": 3,
    },
    {
        "id": 5,
        "client": "Diego Vargas",
        "initials": "DV",
        "service": "Corte + Barba",
        "barber": "Miguel Angel",
        "time": "11:00",
        "duration": 60,
        "status": "confirmed",
        "visits": 8,
    },
    {
        "id": 6,
        "client": "Mariana Lopez",
        "initials": "ML",
        "service": "Balayage",
        "barber": "Laura Garcia",
        "time": "11:30",
        "duration": 150,
        "status": "confirmed",
        "visits": 5,
    },
    {
        "id": 7,
        "client": "Julian Perez",
        "initials": "JP",
        "service": "Corte Clasico",
        "barber": "Carlos Diaz",
        "time": "12:00",
        "duration": 30,
        "status": "pending",
        "visits": 1,
    },
    {
        "id": 8,
        "client": "Natalia Gomez",
        "initials": "NG",
        "service": "Keratina Express",
        "barber": "Sofia Ramos",
        "time": "13:00",
        "duration": 90,
        "status": "pending",
        "visits": 11,
    },
    {
        "id": 9,
        "client": "Ricardo Silva",
        "initials": "RS",
        "service": "Pompadour Premium",
        "barber": "Miguel Angel",
        "time": "14:00",
        "duration": 50,
        "status": "confirmed",
        "visits": 6,
    },
    {
        "id": 10,
        "client": "Isabella Mora",
        "initials": "IM",
        "service": "Arreglo de Barba",
        "barber": "Carlos Diaz",
        "time": "14:30",
        "duration": 20,
        "status": "confirmed",
        "visits": 9,
    },
]
